const Themes = [
    {
      "color-scheme": "light",
      "primary": "#ff79c6",
      "primary-content": "#ffffff",
      "secondary": "#8be9fd",
      "accent": "#ffb86c",
      "neutral": "#f8f8f2",
      "base-100": "#ffffff",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "light"
    },
    {
      "color-scheme": "dark",
      "primary": "#ff79c6",
      "primary-content": "#282a36",
      "secondary": "#8be9fd",
      "accent": "#ffb86c",
      "neutral": "#44475a",
      "base-100": "#282a36",
      "info": "#6272a4",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "dark"
    },
    {
      "color-scheme": "light",
      "primary": "#ff6b6b",
      "primary-content": "#ffffff",
      "secondary": "#ffe66d",
      "accent": "#4ecdc4",
      "neutral": "#1a535c",
      "base-100": "#f7fff7",
      "info": "#4ecdc4",
      "success": "#1a535c",
      "warning": "#ffe66d",
      "error": "#ff6b6b",
      "theme": "cupcake"
    },
    {
      "color-scheme": "light",
      "primary": "#ffbb00",
      "primary-content": "#000000",
      "secondary": "#ffe66d",
      "accent": "#000000",
      "neutral": "#ffffff",
      "base-100": "#ffffff",
      "info": "#000000",
      "success": "#1a535c",
      "warning": "#ffdd00",
      "error": "#ff4444",
      "theme": "bumblebee"
    },
    {
      "color-scheme": "light",
      "primary": "#10b981",
      "primary-content": "#ffffff",
      "secondary": "#3b82f6",
      "accent": "#fbbf24",
      "neutral": "#374151",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "emerald"
    },
    {
      "color-scheme": "light",
      "primary": "#0d9488",
      "primary-content": "#ffffff",
      "secondary": "#3b82f6",
      "accent": "#4b5563",
      "neutral": "#3b82f6",
      "base-100": "#f3f4f6",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "corporate"
    },
    {
      "color-scheme": "dark",
      "primary": "#ff79c6",
      "primary-content": "#282a36",
      "secondary": "#8be9fd",
      "accent": "#ffb86c",
      "neutral": "#44475a",
      "base-100": "#282a36",
      "info": "#6272a4",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "synthwave"
    },
    {
      "color-scheme": "light",
      "primary": "#ff79c6",
      "primary-content": "#282a36",
      "secondary": "#8be9fd",
      "accent": "#ffb86c",
      "neutral": "#44475a",
      "base-100": "#f7fff7",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "retro"
    },
    {
      "color-scheme": "light",
      "primary": "#ffd700",
      "primary-content": "#000000",
      "secondary": "#ff00ff",
      "accent": "#8b0000",
      "neutral": "#ff0000",
      "base-100": "#ffffff",
      "info": "#00ffff",
      "success": "#32cd32",
      "warning": "#ff4500",
      "error": "#ff6347",
      "theme": "cyberpunk"
    },
    {
      "color-scheme": "light",
      "primary": "#fbb6ce",
      "primary-content": "#ffffff",
      "secondary": "#fb7185",
      "accent": "#f472b6",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "valentine"
    },
    {
      "color-scheme": "dark",
      "primary": "#ff4500",
      "primary-content": "#ffffff",
      "secondary": "#ff6347",
      "accent": "#ff4500",
      "neutral": "#1a1a1a",
      "base-100": "#1a1a1a",
      "info": "#ff8c00",
      "success": "#32cd32",
      "warning": "#ff6347",
      "error": "#ff4500",
      "theme": "halloween"
    },
    {
      "color-scheme": "light",
      "primary": "#34d399",
      "primary-content": "#ffffff",
      "secondary": "#4ade80",
      "accent": "#6ee7b7",
      "neutral": "#10b981",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "garden"
    },
    {
      "color-scheme": "dark",
      "primary": "#10b981",
      "primary-content": "#ffffff",
      "secondary": "#4ade80",
      "accent": "#6ee7b7",
      "neutral": "#374151",
      "base-100": "#1f2937",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "forest"
    },
    {
      "color-scheme": "light",
      "primary": "#2563eb",
      "primary-content": "#ffffff",
      "secondary": "#3b82f6",
      "accent": "#2563eb",
      "neutral": "#1e3a8a",
      "base-100": "#ffffff",
      "info": "#2563eb",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "aqua"
    },
    {
      "color-scheme": "dark",
      "primary": "#f8fafc",
      "primary-content": "#1e293b",
      "secondary": "#f8fafc",
      "accent": "#a3e635",
      "neutral": "#3f3f46",
      "base-100": "#18181b",
      "info": "#67e8f9",
      "success": "#86efac",
      "warning": "#fde047",
      "error": "#f87171",
      "theme": "lofi"
    },
    {
      "color-scheme": "light",
      "primary": "#34d399",
      "primary-content": "#ffffff",
      "secondary": "#f472b6",
      "accent": "#f472b6",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "pastel"
    },
    {
      "color-scheme": "dark",
      "primary": "#f97316",
      "primary-content": "#ffffff",
      "secondary": "#eab308",
      "accent": "#8b5cf6",
      "neutral": "#1e293b",
      "base-100": "#18181b",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "fantasy"
    },
    {
      "color-scheme": "light",
      "primary": "#e11d48",
      "primary-content": "#ffffff",
      "secondary": "#be185d",
      "accent": "#7f1d1d",
      "neutral": "#9ca3af",
      "base-100": "#ffffff",
      "info": "#f472b6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "wireframe"
    },
    {
      "color-scheme": "light",
      "primary": "#34d399",
      "primary-content": "#ffffff",
      "secondary": "#22d3ee",
      "accent": "#818cf8",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#818cf8",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "black"
    },
    {
      "color-scheme": "light",
      "primary": "#3b82f6",
      "primary-content": "#ffffff",
      "secondary": "#4ade80",
      "accent": "#f472b6",
      "neutral": "#10b981",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "luxury"
    },
    {
      "color-scheme": "dark",
      "primary": "#f97316",
      "primary-content": "#ffffff",
      "secondary": "#eab308",
      "accent": "#a3e635",
      "neutral": "#1e293b",
      "base-100": "#18181b",
      "info": "#67e8f9",
      "success": "#86efac",
      "warning": "#fde047",
      "error": "#f87171",
      "theme": "dracula"
    },
    {
      "color-scheme": "light",
      "primary": "#6366f1",
      "primary-content": "#ffffff",
      "secondary": "#818cf8",
      "accent": "#4f46e5",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#818cf8",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "cmyk"
    },
    {
      "color-scheme": "dark",
      "primary": "#f43f5e",
      "primary-content": "#ffffff",
      "secondary": "#ec4899",
      "accent": "#d946ef",
      "neutral": "#4b5563",
      "base-100": "#1f2937",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "autumn"
    },
    {
      "color-scheme": "light",
      "primary": "#8b5cf6",
      "primary-content": "#ffffff",
      "secondary": "#a78bfa",
      "accent": "#c084fc",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "business"
    },
    {
      "color-scheme": "dark",
      "primary": "#6366f1",
      "primary-content": "#ffffff",
      "secondary": "#818cf8",
      "accent": "#a78bfa",
      "neutral": "#4b5563",
      "base-100": "#1f2937",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "acid"
    },
    {
      "color-scheme": "light",
      "primary": "#6b7280",
      "primary-content": "#ffffff",
      "secondary": "#4b5563",
      "accent": "#9ca3af",
      "neutral": "#6b7280",
      "base-100": "#f9fafb",
      "info": "#4b5563",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "lemonade"
    },
    {
      "color-scheme": "dark",
      "primary": "#10b981",
      "primary-content": "#ffffff",
      "secondary": "#4ade80",
      "accent": "#6ee7b7",
      "neutral": "#374151",
      "base-100": "#1f2937",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "night"
    },
    {
      "color-scheme": "dark",
      "primary": "#3b82f6",
      "primary-content": "#ffffff",
      "secondary": "#60a5fa",
      "accent": "#93c5fd",
      "neutral": "#374151",
      "base-100": "#1f2937",
      "info": "#60a5fa",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "coffee"
    },
    {
      "color-scheme": "dark",
      "primary": "#a855f7",
      "primary-content": "#ffffff",
      "secondary": "#c084fc",
      "accent": "#a78bfa",
      "neutral": "#4b5563",
      "base-100": "#1f2937",
      "info": "#818cf8",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "winter"
    }
  ];
  
  export default Themes;
  